name: Build ArtPixel Card (SVG)

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Atualiza a cada 12 horas (opcional)
    - cron: "0 */12 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm i

      - name: Generate card.svg
        env:
          CARD_THEME: dark   # transparent | light | dark | emerald
          DURATION: 500s     # velocidade do loop
        run: npm run build:card

      - name: Commit & Push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add card.svg
          git diff --staged --quiet || git commit -m "build: update card.svg [skip ci]"
          git push
